openapi: 3.0.1
info:
  description: >-
    Die API von DIVERA 24/7 bietet zahlreiche Möglichkeiten, um eigene Dienste
    anzubinden und Aktionen auszulösen. Für Testzwecke empfehlen wir Ihnen, eine
    separate Einheit anzulegen. Testeinheiten von zahlenden Kunden werden auf
    Nachfrage kostenfrei hochgestuft.
  version: 4.1.0
  title: DIVERA 24/7 RESTful Webservice für die Passwort Validierung
servers:
  - url: https://app.divera247.com
tags:
  - name: CRUD
    description: Prüfung der übertragenden Passwörter auf Gültigkeit.
  - name: Weitere
    description: Validierung von Passwörtern
paths:
  /api/v2/password/validate:
    post:
      tags:
        - Validierung
      summary: Passwort validieren
      requestBody:
        description: Parameter, die bei der Erstellung der Validierung geprüft werden
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - cluster_id
                - password
                - password_repeat
                - email
              properties:
                user_id:
                  type: string
                  description: Benutzer ID
                cluster_id:
                  type: string
                  description: Cluster ID
                password:
                  type: string
                  description: Passwort
                password_repeat:
                  type: string
                  description: Passwort wiederholung
                email:
                  type: string
                  description: Benutzer Emailadresse
        required: true
      responses:
        200:
          description: successful
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    description: false wenn Fehler in der Validierung
                  errors:
                    type: string
                    description: Fehler der Validierung.
      security:
        - Personal-API-Accesskey: []
    get:
      tags:
        - Validierung
      summary: Passwort validieren
      requestBody:
        description: Parameter, die bei der Erstellung der Validierung geprüft werden
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - cluster_id
                - password
                - password_repeat
                - email
              properties:
                user_id:
                  type: string
                  description: Benutzer ID
                cluster_id:
                  type: string
                  description: Cluster ID
                password:
                  type: string
                  description: Passwort
                password_repeat:
                  type: string
                  description: Passwort wiederholung
                email:
                  type: string
                  description: Benutzer Emailadresse
        required: true
      responses:
        200:
          description: successful
          content:
            "application/json":
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    description: false wenn Fehler in der Validierung
                  errors:
                    type: string
                    description: Fehler der Validierung.
      security:
        - Personal-API-Accesskey: []
components:
  securitySchemes:
    Personal-API-Accesskey:
      type: apiKey
      name: accesskey
      in: query
