name: Build package

on:
  workflow_call:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - name: Install dependencies
        run: uv sync --dev
      - name: ruff check
        run: uv run ruff check
      - name: ruff format --check
        run: uv run ruff format --check
      - name: ty check
        run: uv run ty check

  build:
    needs: lint
    runs-on: ubuntu-latest
    outputs:
      WHL: ${{ steps.filenames.outputs.WHL }}
      TARGZ: ${{ steps.filenames.outputs.TARGZ }}

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7

      - name: Set new version
        if: startsWith(github.ref, 'refs/tags/v')
        run: uv version ${GITHUB_REF/refs\/tags\/v/}

      - name: Build package
        run: uv build

      - name: Set filenames in output
        id: filenames
        run: |
          echo WHL=$(echo dist/*.whl) >> $GITHUB_OUTPUT
          echo TARGZ=$(echo dist/*.tar.gz) >> $GITHUB_OUTPUT
      - name: Archive package
        uses: actions/upload-artifact@v7
        with:
          name: distributions
          path: dist
          retention-days: 5

  tests:
    needs: build

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13", "3.14"]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        distribution: [ "${{ needs.build.outputs.WHL }}",
                        "${{ needs.build.outputs.TARGZ }}" ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          cache-suffix: ${{ matrix.distribution }}
      - uses: actions/download-artifact@v8
        with:
          name: distributions
          path: dist

      - name: Install dependencies
        run: uv sync --group test

      - name: Install package
        run: uv pip install ${{ matrix.distribution }}

      - name: Run pytest
        run: uv run --no-sync pytest
